### PR TITLE
Fullscreen and mobile issues

### PR DESCRIPTION
**Pull request by stephenwf**

### CODE REVIEW

**Comment by atiro** [comment]
Can't find the pull request ID for this branch (assumed it was the commit id but seems not!)

**Comment by stephenwf** [comment]
Ah the version is: `0.1.0-pr.363be20e`

**Comment by atiro** [comment]
Cheers. Getting a react warning that fullscreenable wants 15.4 but seems to have all installed anyway.

**Comment by atiro** [comment]
Still no pins on initial display on Safari (10). Also now losing annotations in full-screen mode in Firefox & Safari (seem to be off-screen)

**Comment by atiro** [comment]
Safari mobile not working at all, page freezes

**Comment by atiro** [comment]
Ah might have messed up CSS, just re-checking

**Comment by atiro** [comment]
Nope, open annotations only appear on non-fullscreen view, but stay on screen if you move to full screen. Opening them in full screen they are not viisble but when you move back to non-fullscreen view they are there.

**Comment by stephenwf** [comment]
Hi @atiro I've found the issue (some transforms had really small floating point numbers or negative 0) and tested on safari, seems to have fixed the issue. Looking into various mobile browsers now

**Comment by atiro** [comment]
Pull request version please (where is that in the page ?! Sure it's somewhere)

**Comment by stephenwf** [comment]
@atiro Latest version is at `0.1.0-pr.2635086e`

**Comment by atiro** [comment]
Can't test on Safari at the moment but seems to have regressed on Firefox 58.0.2, getting broken half-screen when going to full screen. Also new error: "Warning: `NaN` is an invalid value for the `maxHeight` css style property.

**Comment by atiro** [comment]
Looking good again on Firefox, will test Safari on Monday. Almost there!

**Pull request merged**
