### PR TITLE
VA Bug fixes for safari and mobile

### LINKED ISSUE #5: Responsive design
> Designed responsively: on desktop, the annotation body should appear in the top left when a marker is selected. In mobile view, annotations should appear at the bottom, to avoid obscuring the image. Annotation may take up entire canvas in mobile view - (If this is possible through configurable CSS, this functionality is not required)

A lot of this will be configurable with CSS, but we will include basic positioning examples.

### LINKED ISSUE #23: Safari: Fullscreen API not working correctly
There are some errors when viewing the documentation on mobile safari, related to the fullscreen API. `cannot call on of undefined` or something similar. Also potentially related, the V&A example does not load at all (probably caused by this error) and on safari desktop its very unstable, sometimes causing crashes. Lots of RAF requests (~60k per frame) might be related to OSD.

### LINKED ISSUE #28: Firefox 58.0.2 - Fullscreen mode does not work
If select a annotation and then full screen 

The annotation box remains visible but the screen goes blank, when click on blank screen the canvas appears in the bottom left corner

Need to press esc to get out of full screen

### LINKED ISSUE #29: Firefox 58.0.2 - variation 3 peg is slightly out
the outline of the peg is slightly off when viewed in firefox for variation 3

### LINKED ISSUE #43: Fixed size option crashes safari
I think Safari is really struggling with the scaling up and scaling down in a single operation. Need to look into a different approach for fixed sized zooming (like resizing elements individually).

### LINKED ISSUE #49: Scroll bar not visible in Chrome
On the patchwork example, the scroll bar is not appearing in the pop-up annotations on Chrome.

### PR DESCRIPTION
**Pull request by stephenwf**
- Fixes #5 (example mobile styles)
- Fixes #23
- Fixes #28
- Fixes #29 
- Fixes #43 
- Fixes #48 (not yet tested)
- Fixes #49

### CODE REVIEW

**Comment by stephenwf** [comment]
@hollyhyams I've fixed some issues with the performance, which has fixed the issues on safari and Firefox. I've tested on iOS 11.2 Safari, but not yet on Android (although both webkit browsers, I expect them both to be working as expected now!) 

Here is the preview link for this pull request: 
https://deploy-preview-51--canvas-panel.netlify.com/#/examples/patchwork

**Comment by atiro** [comment]
Can you push a new build upto npm as it's easier to install from there.

**Comment by stephenwf** [comment]
Hi @atiro, we've recently added continuious deployment, so you can install this pull request by targeting `@canvas-panel/patchwork-plugin@pr-51` (ID 51 from the pull request URL.)

You can also target the exact version:
```
npm install @canvas-panel/patchwork-plugin@0.1.0-pr.c4d82da1
```

You can get the exact versions from any command line by running:
```
npm view @canvas-panel/patchwork-plugin dist-tags
```

To see all the versions available to install

**Comment by atiro** [comment]
Am still seeing odd behaviour in firefox on both mobile & desktop. The image loads in full screen and then is immediately obscured by a block. Can't click on pins.

**Comment by atiro** [comment]
In Safari on mobile pins don't appear in full screen mode. On desktop they don't always appear when you switch between full screen/inset mode, or sometimes seem to be at the wrong size for the display.

**Comment by stephenwf** [comment]
@atiro I'll take another look, would you be able to provide OS's and versions for the browsers you're testing?

**Comment by atiro** [comment]
Chrome just works!

**Comment by atiro** [comment]
Sorry @stephenwf , added now

**Comment by stephenwf** [comment]
Thanks @atiro the fullscreen API is a bit frustrating, quite a lot of differences across browsers! Will see what I can do

**Comment by atiro** [comment]
Any luck with fullscreen @stephenwf ?

**Comment by stephenwf** [comment]
Morning @atiro

I've pushed a fix that I think was causing issues on non-chrome browsers when going into fullscreen. The build is finishing publishing, I'll post the NPM versions once its finished for you to test.

**Comment by stephenwf** [comment]
Here's the NPM version:
```
npm install @canvas-panel/patchwork-plugin@0.1.0-pr.4268aa7c
```

**Comment by atiro** [comment]
Getting there, works on firefox now if you zoom initially before going into full-screen, but otherwise there is still this strange overlay that appears over the top half of the image and stops any interaction:

peek 2018-03-14 16-31

**Comment by atiro** [comment]
Likewise on Safari (desktop), the pins only appear once you start zooming.

**Comment by atiro** [comment]
Looking more on firefox desktop, the canvas size is wrong when it's broken:

<canvas style="background: transparent none repeat scroll 0% 0%; border: medium none; margin: 0px; padding: 0px; position: absolute; width: 100%; height: 100%;" width="1200" height="1150"></canvas>

It's all fine when it is:

<canvas style="background: transparent none repeat scroll 0% 0%; border: medium none; margin: 0px; padding: 0px; position: absolute; width: 100%; height: 100%;" width="1680" height="1050"></canvas>

I can't see what triggers the different sizes though. Sometimes it's working fine switching back and forther between small/full screen but then when you scroll down the page and open Full screen again it's the wrong size.

**Comment by stephenwf** [comment]
Hi @atiro 

Having trouble replicating that particular issue reliably. Would it be possible for you to test the deploy preview: https://deploy-preview-51--canvas-panel.netlify.com/#/examples/patchwork and see if you find the bug appearing there, as that is what I'm using for my own testing.

I will look what we can do about the viewport not resizing, I think there might be 2 things conflicting here as we do set a max width of 1200 somewhere on the page to fit the content. I hope the latest fixes solve it, but I will take another look again tomorrow.

**Comment by atiro** [comment]
Looking much better on firefox, can't break it so far! Will test on Safari tomorrow. (deploy preview also working fine in Firefox FYI)

**Comment by atiro** [comment]
All good on firefox desktop & mobile now. Last one is Safari. Pins are not initially showing until you startzooming in. The pins also vanish when you exit fullscreen.

Safari on mobile seems to lose the image entirely now when you click on View in Fullscreen

**Comment by atiro** [comment]
Also same issues with Safari (desktop, 10.02) testing on your demo page (no initial pins).

Safari 11.0.3 is all fine (desktop)

**Comment by stephenwf** [comment]
Hi @atiro ah I see, I was testing on Safari 11, will go through from Safari 8+ and see what sort of improvements can be made

**Comment by stephenwf** [comment]
Hi @atiro I've merged in the current set of fixes, so we can get those updates onto the wider canvas panel code for the example site. I went through safari 9 and 10 and I was able to replicate the bug every 4-5 times I opened in fullscreen. I think I have an idea of where the problem is, I will open a new Pull request with that change shortly.

**Pull request merged**
