### PR TITLE
Feature/slideshow package

### PR DESCRIPTION
**Pull request by adam-digirati**
Based on the feature/balenciaga-mobile Created the @canvas-panel/slideshow package.

### CODE REVIEW

**Comment by stephenwf** [comment]
Final piece I think would be a component that gives you a single component wrapper around these, like the previous plugins and also an imperative JS plugin that can just be called (for use without touching React). Looks good though, nice spot on those IE10 fixes 👍

**Comment by adam-digirati** [comment]
@stephenwf added the UMD example, and updated nwb to v 0.23 in order to be able to use UMD modules properly...

I'll update the patchwork and the full page plugin as well to use a separate entry for UMD, because they also return undefined...

**Comment by adam-digirati** [comment]
in order to fix the styleguide:build issue please approve my pull request on
https://github.com/stephenwf/create-nwb-webpack-config/pull/2

**Comment by adam-digirati** [comment]
@stephenwf Could you please merge create-nwb-webpack-config as well...

**Pull request merged**
